### ISSUE TITLE
Not creating "yoga.dll" on build

### ISSUE THREAD

**Issue by Charanor** [IceReaper/YogaSharp#3]
Perhaps I've misunderstood something but when I add this package to my project and build, it fails with the exception `System.DllNotFoundException: Unable to load DLL 'yoga': The specified module could not be found.`. This is because no dll `yoga.dll` is generated. Are we supposed to build it ourselves? I find the original Yoga repo incredibly confusing, and the instructions are super unclear - especially for Windows.

**Comment by Charanor** [comment]
Nevermind! Had a typo in my csproj file. For anyone that's wondering you have to add this to your .csproj file (just copy paste, don't type like I did lol)

```
<PropertyGroup>
    <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Windows'))">win-x64</TargetPlatform>
    <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Linux'))">linux-x64</TargetPlatform>
    <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('OSX'))">osx-x64</TargetPlatform>
</PropertyGroup>
```

**Comment by arolson101** [comment]
> Nevermind! Had a typo in my csproj file. For anyone that's wondering you have to add this to your .csproj file (just copy paste, don't type like I did lol)
> 
> ```
> <PropertyGroup>
>     <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Windows'))">win-x64</TargetPlatform>
>     <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Linux'))">linux-x64</TargetPlatform>
>     <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('OSX'))">osx-x64</TargetPlatform>
> </PropertyGroup>
> ```

@Charanor  - Could you clarify which csproj you're adding these lines to and what they do?

**Comment by Charanor** [comment]
> > Nevermind! Had a typo in my csproj file. For anyone that's wondering you have to add this to your .csproj file (just copy paste, don't type like I did lol)
> > ```
> > <PropertyGroup>
> >     <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Windows'))">win-x64</TargetPlatform>
> >     <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Linux'))">linux-x64</TargetPlatform>
> >     <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('OSX'))">osx-x64</TargetPlatform>
> > </PropertyGroup>
> > ```
> 
> @Charanor - Could you clarify which csproj you're adding these lines to and what they do?

I added these to **my** main project's `.csproj` file (the project that has this package as dependency, **not** the .csproj in **this** package). I can't tell you exactly what it does, but from reading it I assume it decides which build process to run, that way the package knows which .dll to generate :)
